name: Production

on:
  workflow_dispatch:

jobs:
  merge:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Merge Branch into Main
      run: |
        git fetch origin dev:temp_branch
        git checkout main
        git merge temp_branch
        git push origin main

    - name: Discord Action
      run: |
        echo "Result=\"[Frontend released to PROD]\""
      shell: bash
      env:
        COMMIT_AUTHOR: ${{ github.event.commits[0].author.name }}
        COMMIT_MSG: ${{ github.event.commits[0].message }}

    - name: Discord Notification
      uses: Ilshidur/action-discord@0.3.2
      with:
        args: ${{ env.Result }}
      env:
        DISCORD_WEBHOOK: https://discord.com/api/webhooks/1128921696687104092/VZiM0hi7oX6QRTETa7sa78lPSNKkHvLPi1MqgOF7Au-JO9auq3328JBOYm3_z2uAwZXY