name: Build on Pull Request

on:
  pull_request:
    branches:
      - dev # or the default branch of your repository, e.g., 'master'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '18' # You can specify your desired Node.js version here

    - name: Install Dependencies
      run: npm install

    - name: Run Build
      run: npm run build
